### ISSUE TITLE
Support for maps

### ISSUE THREAD

**Issue by asdine** [asdine/genji#1]
Example:

```go
// compile time map
type MyMap map[string]int
```

```sh
genji record -f mymap.go -t MyMap
```

**Comment by nustiueudinastea** [comment]
At the moment Genji does not work with structs that have fields that are maps. Will this issue improve this? Thanks!

**Comment by asdine** [comment]
@nustiueudinastea Actually no, this issue is obsolete, I'll close it right now.
Could you open a new issue and give an example of your problem? I'm a bit surprised that it doesn't work with nested maps, you might have found a bug. Thank you!
