### ISSUE TITLE
Add Badger engine

### ISSUE THREAD

**Issue by asdine** [asdine/genji#22]

**Comment by nobita0590** [comment]
Hi. that is great work. How long I should wait for Badger engine

**Comment by asdine** [comment]
This will be done in the v0.2.0 👍 
To be able to add Badger correctly, we need this issue to land https://github.com/dgraph-io/badger/issues/786, it will help implementing the index system, but it's not mandatory to have a basic badger engine in Genji

**Comment by nobita0590** [comment]
yes. thank you

**Comment by asdine** [comment]
I've finally implemented this for the v0.1.0 milestone, you can use the Badger engine 👍

**Comment by nobita0590** [comment]
the project's API is stable and it is ready for production. I want to confirm before I use it. thank you

**Comment by asdine** [comment]
No it's not stable yet, database format and API is subject to change in the coming days / months
