### ISSUE TITLE
Contribution & Communication

### ISSUE THREAD

**Issue by BigJk** [asdine/genji#27]
Hello @asdine 

as someone who is using your awesome storm since 2016 I'm really interested in genji. I would like to know if you are searching for contributors and if there is any platform for genji-interested people to communicate (Slack, Discord, IRC) in order to avoid bloating the Issues 😄

**Comment by asdine** [comment]
Hey @BigJk 

I'm glad you are interested in the project :+1: 
I have created a channel on the gophers slack to communicate about the project. Here is the address: https://gophers.slack.com/messages/CKPCYQFE0
Also, I have added the link in the readme
