### ISSUE TITLE
Support Ristretto as main memory engine

### ISSUE THREAD

**Issue by asdine** [asdine/genji#39]

**Comment by rugwirobaker** [comment]
Hello, I'm on some kind self teaching path in systems development and  surprisingly I have found out storage systems are a good way to understand how things like memory and data structures work in real world systems. Can I expect help if I took this upon myself? Disclaimer: might not be perfect but will work on it until it is.

**Comment by asdine** [comment]
Unfortunately, I have misread Ristretto's documentation: It doesn't support iteration on the cache keys and thus can't be used for this purpose.

@rugwirobaker Sorry for the late reply, I'm closing this now but I'll mark any issue I believe is doable without too much context as `good first issue` and will be available here or on Slack to answer questions :+1:

**Comment by rugwirobaker** [comment]
No worries 😊👍. I will wait for my opportunity.
